# https://github.com/strimzi/strimzi-kafka-operator/issues/4716

# Mount this release to the secret of a service account that is whitelisted by external Vault clusters

# At the early stage of this project, there is already a set of Service Account whitelisted by all external Vault cluster for batch ingestion,
# plus, Strimizi force a new Service Account created for every Kafka Connect Deployment.
# Therefore, to aviod the trouble of whitelisting new Service Account on external Vault cluster,
# the existing whitelisted Service Account's token is used, via the following Serect resrouce

# apiVersion: v1
# kind: Secret
# metadata:
#   name: streaming-secret-{{ .Values.vaultServiceAccountName }}-{{ .Values.appName }}
#   annotations:
#     kubernetes.io/service-account.name: "{{ .Values.vaultServiceAccountName }}"
# type: kubernetes.io/service-account-token

# However, since there is already existing Secret storing the Service Account token in the same "data-lake" namespace,
# for simplisity, this deployment will directly mount it withouting creating same Secret for each new release 